import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppNavProvider } from "./contexts/AppNavContext";
import { LocaleProvider } from "./contexts/LocaleContext";
import GlobalNav from "./GlobalNav";
import ConnectionGate from "./ConnectionGate";
import NotificationsBoot from "./NotificationsBoot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// VELIS sadece portre bir telefon uygulaması olarak tasarlandı.
// - width: 'device-width' -> sabit 393 yerine cihazın gerçek genişliği
//   kullanılıyor; aksi halde iPhone 17 / Pro Max gibi daha geniş cihazlarda
//   sayfa 393px'e sığdırılıp ölçekleniyor ve kenarlar kırpılmış görünüyordu.
// - viewportFit: 'cover' -> Dynamic Island / home indicator arkasına da
//   çiziyor AMA bunun karşılığında env(safe-area-inset-*) artık gerçek
//   değerler döndürüyor (tüm ekranlardaki safe-area padding kodu buna bağlı).
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LocaleProvider>
          <AppNavProvider>
            <ConnectionGate>
              {children}
              <GlobalNav />
              <NotificationsBoot />
            </ConnectionGate>
          </AppNavProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
